version: '3'

services:
  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address :9090
    expose:
      - "9000"
      - "9090"
    ports:
      - 9090:9090
      - 9000:9000
    volumes:
      - ${DATA_PATH}/.data/minio/data:/data
      - ${DATA_PATH}/.data/minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - todolist

  monogodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${DATA_PATH}/.data/mongo/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    networks:
      - todolist


networks:
  todolist:
    driver: bridge